[project]
name = "tiktok-uploader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]

[project.scripts]
upload-inbox = "uploader:main"
upload-public = "uploader:main_second"
